//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.AirPorts = new HashSet<AirPort>();
        }
    
        public int city_id { get; set; }
        public int city_cntr_id_FK { get; set; }
        public string city_name { get; set; }
        public Nullable<long> city_population { get; set; }
        public System.DateTime city_GMT { get; set; }
        public string city_signGMT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirPort> AirPorts { get; set; }
        public virtual Country Country { get; set; }
    }
}
