//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Events = new HashSet<Event>();
            this.Tickets = new HashSet<Ticket>();
            this.UnexpectedEvents = new HashSet<UnexpectedEvent>();
        }
    
        public int fl_id { get; set; }
        public int fl_airc_id_FK { get; set; }
        public int fl_pln_id_FK { get; set; }
        public int fl_airP_id_FK { get; set; }
        public string fl_type { get; set; }
        public System.DateTime fl_dateTimeStart { get; set; }
        public System.DateTime fl_duration { get; set; }
        public System.DateTime fl_dateTimeArrival { get; set; }
        public int fl_numOfFlights { get; set; }
        public System.DateTime fl_periodicity { get; set; }
        public decimal fl_priceEconom { get; set; }
        public decimal fl_priceBusiness { get; set; }
        public decimal fl_priceFirst { get; set; }
        public System.DateTime fl_dateTimeStartGMT { get; set; }
        public System.DateTime fl_dateTimeArrivalGMT { get; set; }
        public string fl_status { get; set; }
    
        public virtual Aircompany Aircompany { get; set; }
        public virtual AirPort AirPort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Plane Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnexpectedEvent> UnexpectedEvents { get; set; }
    }
}
