//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airportDBEntities : DbContext
    {
        public airportDBEntities()
            : base("name=airportDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircompany> Aircompanies { get; set; }
        public virtual DbSet<AirPort> AirPorts { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<UnexpectedEvent> UnexpectedEvents { get; set; }
    }
}
