//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int pass_id { get; set; }
        public int pass_dT_id_FK { get; set; }
        public string pass_lastName { get; set; }
        public string pass_firstName { get; set; }
        public System.DateTime pass_birthDate { get; set; }
        public string pass_gender { get; set; }
        public string pass_docNumber { get; set; }
    
        public virtual DocType DocType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
