//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int tkt_id { get; set; }
        public int tkt_fl_id_FK { get; set; }
        public int tkt_pass_id_FK { get; set; }
        public int tkt_br_id_FK { get; set; }
        public string tkt_class { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
