//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airportApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnexpectedEvent
    {
        public int uE_id { get; set; }
        public int uE_fl_id_FK { get; set; }
        public string uE_eventType { get; set; }
        public System.DateTime uE_dateTimeEvent { get; set; }
        public System.DateTime uE_Duration { get; set; }
        public string ue_reason { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
